server:
  http_listen_port: 3200
  log_level: debug
  log_request_headers: true
  log_request_at_info_level_enabled: true
  log_format: json
distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://host.docker.internal:9090/api/v1/write
        send_exemplars: true
overrides:
  metrics_generator_processors: [service-graphs, span-metrics, local-blocks]
#  generate_native_histograms: both
